import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";

const TERMS_EN = `# Terms of Service

**Platform:** AgentPick  
**Domain:** agentpick.co  
**Effective Date:** March 11, 2026  
**Last Updated:** March 11, 2026  
**Contact:** legal@agentpick.co

---

## 1. Introduction and Acceptance

These Terms of Service ("Terms") govern your use of AgentPick ("Platform", "we", "us"), accessible at agentpick.co. By creating an account or using the Platform in any way, you agree to be bound by these Terms.

If you do not agree, do not use the Platform.

These Terms apply to all users, including buyers (subscribers) and creators (publishers of AI agents and skills).

> **Note:** AgentPick is in the process of formal incorporation. Until incorporated, the Platform is operated by its founders under Italian law.

---

## 2. Who Can Use AgentPick

To use AgentPick, you must:

- Be at least **16 years old** (or the applicable age of digital consent in your country)
- Have the legal capacity to enter into binding agreements
- Not be prohibited from using the Platform under applicable law
- Provide accurate and complete information when registering

By registering, you represent and warrant that you meet these requirements.

---

## 3. Account Registration

You are responsible for maintaining the confidentiality of your account credentials. You agree to:

- Provide accurate, current, and complete information
- Keep your password secure and not share it with third parties
- Notify us immediately at legal@agentpick.co if you suspect unauthorised access to your account
- Accept responsibility for all activities that occur under your account

We reserve the right to suspend or terminate accounts that contain false information or that violate these Terms.

---

## 4. Subscription Model

### 4.1 How It Works

AgentPick operates on a **subscription basis**. Buyers pay a recurring subscription fee to access agents and skills published on the Platform. Creators earn revenue from subscriptions generated by their published content.

### 4.2 Pricing

Subscription prices are published on the Platform and may change with at least **30 days' notice**. Existing subscriptions will not be affected until the next renewal cycle.

### 4.3 Billing

Subscriptions are billed in advance on a monthly or annual basis, depending on the plan selected. Payment is processed by our third-party payment provider.

### 4.4 Cancellation and Refunds

You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not offer refunds for unused portions of a subscription period, except where required by applicable law (including EU consumer rights regulations).

For EU consumers exercising the right of withdrawal under Directive 2011/83/EU: you have 14 days from the start of your subscription to withdraw without giving a reason. If you have already begun using the service within this period, a proportional charge may apply.

---

## 5. Intellectual Property

### 5.1 Platform Content

All content owned by AgentPick — including the Platform's code, design, logo, branding, and documentation — is our exclusive property or licensed to us. You may not copy, reproduce, modify, or distribute this content without our written consent.

### 5.2 Creator Content

Creators retain full intellectual property ownership of the agents and skills they publish. By publishing on AgentPick, creators grant us a **non-exclusive, royalty-free, worldwide licence** to display, promote, and deliver their content through the Platform. This licence ends when the creator removes their content from the Platform.

### 5.3 User Content

Any feedback, suggestions, or ideas you submit to us may be used by us freely without obligation to you.

### 5.4 Infringement Claims

If you believe any content on the Platform infringes your intellectual property rights, contact us at legal@agentpick.co with details of the alleged infringement. We will investigate and respond promptly.

---

## 6. Prohibited Uses

You may not use AgentPick to:

- Violate any applicable law or regulation
- Publish or distribute malware, harmful code, or deceptive agents
- Infringe the intellectual property rights of any third party
- Engage in fraud, phishing, or other deceptive practices
- Harass, threaten, or harm other users
- Circumvent any access controls or security measures
- Scrape, extract, or systematically collect Platform data without authorisation
- Create accounts for the purpose of spam or artificial inflation of metrics
- Publish content that is illegal, obscene, defamatory, or that promotes violence or discrimination
- Impersonate any person or entity

Violation of this section may result in immediate account termination and, where appropriate, legal action.

---

## 7. Creator Responsibilities

Creators are solely responsible for:

- The accuracy, legality, and quality of content they publish
- Ensuring their agents and skills do not infringe any third-party rights
- Complying with all applicable laws, including export control laws
- Responding to takedown requests in a timely manner

AgentPick is not liable for creator content. We reserve the right to remove any content that violates these Terms or applicable law, at our sole discretion.

---

## 8. Platform Availability

We aim to maintain high availability but do not guarantee uninterrupted access to the Platform. Scheduled maintenance, updates, or unforeseen technical issues may cause temporary downtime. We will notify users of planned maintenance in advance where possible.

---

## 9. Limitation of Liability

To the maximum extent permitted by applicable law:

- AgentPick is provided **"as is"** without warranties of any kind, express or implied
- We do not warrant that the Platform will be error-free, uninterrupted, or free of viruses
- We are not liable for any **indirect, incidental, special, consequential, or punitive damages**, including loss of profits, data, or goodwill
- Our total liability to you for any claim arising out of or relating to these Terms or the Platform shall not exceed the **amount you paid to us in the 12 months preceding the claim**

Nothing in these Terms limits or excludes liability where this is not permitted by law, including:

- Liability for death or personal injury caused by our negligence
- Liability for fraud or fraudulent misrepresentation
- Any other liability that cannot be excluded under Italian or EU law

EU consumers retain all statutory rights that cannot be waived by contract.

---

## 10. Indemnification

You agree to indemnify and hold harmless AgentPick and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable legal fees) arising from:

- Your use of the Platform
- Your content published on the Platform
- Your violation of these Terms
- Your violation of any third-party rights

---

## 11. Termination

### 11.1 By You

You may close your account at any time by contacting us at legal@agentpick.co or through your account settings. Closing your account cancels any active subscription at the end of the current billing period.

### 11.2 By Us

We may suspend or terminate your account, with or without notice, if:

- You violate these Terms
- We are required to do so by law
- We reasonably suspect fraud or harmful conduct
- Your account has been inactive for more than 24 months

### 11.3 Effect of Termination

Upon termination, your right to use the Platform ceases immediately. Creator content may be removed from the Platform within 30 days. Provisions that by their nature survive termination (including IP ownership, limitation of liability, and governing law) shall remain in effect.

---

## 12. Changes to These Terms

We may update these Terms from time to time. We will notify you of material changes via email or a prominent notice on the Platform at least **14 days before** the changes take effect. Your continued use of the Platform after that date constitutes acceptance of the revised Terms.

If you do not accept the changes, you must stop using the Platform and close your account before the effective date.

---

## 13. Governing Law and Disputes

These Terms are governed by **Italian law** and, where applicable, **EU law** (including consumer protection regulations).

Any dispute arising from these Terms or your use of the Platform shall first be attempted to be resolved amicably by contacting legal@agentpick.co.

If amicable resolution fails, disputes shall be subject to the exclusive jurisdiction of the **courts of Italy**, unless mandatory EU consumer protection rules provide otherwise (in which case you may also bring proceedings in the courts of your country of residence).

EU consumers also have the right to use the **EU Online Dispute Resolution (ODR) platform**: https://ec.europa.eu/consumers/odr

---

## 14. Miscellaneous

- **Entire Agreement:** These Terms, together with the Privacy Policy, Cookie Policy, and (for creators) the Creator Agreement, constitute the entire agreement between you and AgentPick.
- **Severability:** If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force.
- **No Waiver:** Our failure to enforce any right or provision does not constitute a waiver of that right.
- **Assignment:** You may not assign your rights under these Terms without our written consent. We may assign our rights in connection with a merger, acquisition, or sale of assets.
- **Language:** The authoritative version of these Terms is in English. The Italian translation is provided for convenience.

---

## 15. Contact

**AgentPick**  
agentpick.co  
Email: legal@agentpick.co`;

const TERMS_IT = `# Termini di Servizio

**Piattaforma:** AgentPick  
**Dominio:** agentpick.co  
**Data di entrata in vigore:** 11 marzo 2026  
**Ultimo aggiornamento:** 11 marzo 2026  
**Contatto:** legal@agentpick.co

---

## 1. Introduzione e Accettazione

I presenti Termini di Servizio ("Termini") disciplinano l'utilizzo di AgentPick ("Piattaforma", "noi", "ci"), accessibile all'indirizzo agentpick.co. Creando un account o utilizzando la Piattaforma in qualsiasi modo, accetti di essere vincolato dai presenti Termini.

Se non sei d'accordo, non utilizzare la Piattaforma.

I presenti Termini si applicano a tutti gli utenti, inclusi gli acquirenti (abbonati) e i creatori (pubblicatori di agenti AI e skill).

> **Nota:** AgentPick è in fase di costituzione formale. Fino al completamento della procedura, la Piattaforma è gestita dai suoi fondatori ai sensi della legge italiana.

---

## 2. Chi Può Utilizzare AgentPick

Per utilizzare AgentPick, devi:

- Avere almeno **16 anni** (o l'età del consenso digitale applicabile nel tuo Paese)
- Avere la capacità giuridica di stipulare accordi vincolanti
- Non essere escluso dall'utilizzo della Piattaforma dalla legge applicabile
- Fornire informazioni accurate e complete in fase di registrazione

Registrandoti, dichiari e garantisci di soddisfare questi requisiti.

---

## 3. Registrazione dell'Account

Sei responsabile della riservatezza delle tue credenziali di accesso. Accetti di:

- Fornire informazioni accurate, aggiornate e complete
- Mantenere la tua password sicura e non condividerla con terzi
- Notificarci immediatamente all'indirizzo legal@agentpick.co in caso di accesso non autorizzato al tuo account
- Accettare la responsabilità per tutte le attività svolte con il tuo account

Ci riserviamo il diritto di sospendere o terminare gli account che contengono informazioni false o che violano i presenti Termini.

---

## 4. Modello di Abbonamento

### 4.1 Come Funziona

AgentPick opera su base **abbonamento**. Gli acquirenti pagano una quota di abbonamento ricorrente per accedere agli agenti e alle skill pubblicati sulla Piattaforma. I creatori guadagnano ricavi dagli abbonamenti generati dai loro contenuti pubblicati.

### 4.2 Prezzi

I prezzi degli abbonamenti sono pubblicati sulla Piattaforma e possono variare con un preavviso di almeno **30 giorni**. Gli abbonamenti attivi non saranno interessati fino al successivo ciclo di rinnovo.

### 4.3 Fatturazione

Gli abbonamenti vengono fatturati anticipatamente su base mensile o annuale, a seconda del piano selezionato. Il pagamento viene elaborato dal nostro fornitore di servizi di pagamento terzo.

### 4.4 Cancellazione e Rimborsi

Puoi cancellare il tuo abbonamento in qualsiasi momento. La cancellazione ha effetto alla fine del periodo di fatturazione in corso. Non offriamo rimborsi per le porzioni inutilizzate del periodo di abbonamento, salvo quanto richiesto dalla legge applicabile (incluse le normative europee sui diritti dei consumatori).

Per i consumatori UE che esercitano il diritto di recesso ai sensi della Direttiva 2011/83/UE: hai 14 giorni dall'inizio dell'abbonamento per recedere senza fornire alcuna motivazione. Se hai già iniziato a utilizzare il servizio entro questo periodo, potrebbe essere applicato un addebito proporzionale.

---

## 5. Proprietà Intellettuale

### 5.1 Contenuti della Piattaforma

Tutti i contenuti di proprietà di AgentPick — inclusi codice, design, logo, identità visiva e documentazione della Piattaforma — sono di nostra esclusiva proprietà o ci sono stati licenziati. Non puoi copiare, riprodurre, modificare o distribuire tali contenuti senza il nostro consenso scritto.

### 5.2 Contenuti dei Creatori

I creatori mantengono la piena titolarità della proprietà intellettuale degli agenti e delle skill che pubblicano. Pubblicando su AgentPick, i creatori ci concedono una **licenza non esclusiva, senza royalty, a livello mondiale** per visualizzare, promuovere e distribuire i loro contenuti attraverso la Piattaforma. Questa licenza termina quando il creatore rimuove il proprio contenuto dalla Piattaforma.

### 5.3 Contenuti degli Utenti

Qualsiasi feedback, suggerimento o idea che ci invii potrà essere utilizzato da noi liberamente, senza alcun obbligo nei tuoi confronti.

### 5.4 Reclami per Violazione

Se ritieni che un contenuto sulla Piattaforma violi i tuoi diritti di proprietà intellettuale, contattaci all'indirizzo legal@agentpick.co con i dettagli della presunta violazione. Indagheremo e risponderemo tempestivamente.

---

## 6. Utilizzi Vietati

Non puoi utilizzare AgentPick per:

- Violare qualsiasi legge o normativa applicabile
- Pubblicare o distribuire malware, codice dannoso o agenti ingannevoli
- Violare i diritti di proprietà intellettuale di terzi
- Porre in essere frodi, phishing o altre pratiche ingannevoli
- Molestare, minacciare o danneggiare altri utenti
- Aggirare qualsiasi controllo di accesso o misura di sicurezza
- Eseguire scraping, estrarre o raccogliere sistematicamente dati dalla Piattaforma senza autorizzazione
- Creare account per spam o gonfiare artificialmente le metriche
- Pubblicare contenuti illegali, osceni, diffamatori o che promuovano violenza o discriminazione
- Impersonare qualsiasi persona o entità

La violazione di questa sezione può comportare la risoluzione immediata dell'account e, ove appropriato, l'avvio di azioni legali.

---

## 7. Responsabilità dei Creatori

I creatori sono gli unici responsabili:

- Dell'accuratezza, della legalità e della qualità dei contenuti che pubblicano
- Del fatto che i loro agenti e skill non violino diritti di terzi
- Del rispetto di tutte le leggi applicabili, incluse le normative sul controllo delle esportazioni
- Della risposta tempestiva alle richieste di rimozione

AgentPick non è responsabile per i contenuti dei creatori. Ci riserviamo il diritto di rimuovere qualsiasi contenuto che violi i presenti Termini o la legge applicabile, a nostra esclusiva discrezione.

---

## 8. Disponibilità della Piattaforma

Puntiamo a garantire un'elevata disponibilità, ma non garantiamo un accesso ininterrotto alla Piattaforma. Manutenzioni programmate, aggiornamenti o problemi tecnici imprevisti potrebbero causare interruzioni temporanee. Ove possibile, informeremo gli utenti in anticipo delle manutenzioni programmate.

---

## 9. Limitazione di Responsabilità

Nella misura massima consentita dalla legge applicabile:

- AgentPick è fornita **"così com'è"** senza garanzie di alcun tipo, esplicite o implicite
- Non garantiamo che la Piattaforma sia priva di errori, ininterrotta o esente da virus
- Non siamo responsabili per **danni indiretti, incidentali, speciali, consequenziali o punitivi**, inclusa la perdita di profitti, dati o avviamento commerciale
- La nostra responsabilità totale nei tuoi confronti per qualsiasi reclamo derivante dai presenti Termini o dalla Piattaforma non supererà **l'importo che ci hai corrisposto nei 12 mesi precedenti il reclamo**

Nulla nei presenti Termini limita o esclude la responsabilità laddove ciò non sia consentito dalla legge, inclusa:

- La responsabilità per morte o lesioni personali causate da nostra negligenza
- La responsabilità per frode o dichiarazioni fraudolente
- Qualsiasi altra responsabilità non escludibile ai sensi della legge italiana o dell'UE

I consumatori UE mantengono tutti i diritti legali che non possono essere derogati contrattualmente.

---

## 10. Manleva

Accetti di manlevare e tenere indenne AgentPick e i suoi dirigenti, amministratori, dipendenti e agenti da qualsiasi reclamo, danno, perdita o spesa (incluse le ragionevoli spese legali) derivanti da:

- Il tuo utilizzo della Piattaforma
- I tuoi contenuti pubblicati sulla Piattaforma
- La tua violazione dei presenti Termini
- La tua violazione dei diritti di terzi

---

## 11. Risoluzione

### 11.1 Da Parte Tua

Puoi chiudere il tuo account in qualsiasi momento contattandoci all'indirizzo legal@agentpick.co o tramite le impostazioni del tuo account. La chiusura dell'account annulla qualsiasi abbonamento attivo alla fine del periodo di fatturazione in corso.

### 11.2 Da Parte Nostra

Potremmo sospendere o terminare il tuo account, con o senza preavviso, qualora:

- Tu violi i presenti Termini
- Ne siamo obbligati per legge
- Abbiamo ragionevole motivo di sospettare frodi o condotte dannose
- Il tuo account sia rimasto inattivo per più di 24 mesi

### 11.3 Effetti della Risoluzione

Alla risoluzione, il tuo diritto di utilizzare la Piattaforma cessa immediatamente. I contenuti dei creatori possono essere rimossi dalla Piattaforma entro 30 giorni. Le disposizioni che per loro natura sopravvivono alla risoluzione (incluse la proprietà intellettuale, la limitazione di responsabilità e la legge applicabile) rimarranno in vigore.

---

## 12. Modifiche ai Presenti Termini

Potremmo aggiornare i presenti Termini di tanto in tanto. Ti informeremo delle modifiche sostanziali via email o tramite un avviso ben visibile sulla Piattaforma almeno **14 giorni prima** dell'entrata in vigore delle modifiche. Il tuo utilizzo continuato della Piattaforma dopo tale data costituisce accettazione dei Termini aggiornati.

Se non accetti le modifiche, devi smettere di utilizzare la Piattaforma e chiudere il tuo account prima della data di entrata in vigore.

---

## 13. Legge Applicabile e Controversie

I presenti Termini sono disciplinati dalla **legge italiana** e, ove applicabile, dal **diritto dell'UE** (incluse le normative sulla protezione dei consumatori).

Qualsiasi controversia derivante dai presenti Termini o dall'utilizzo della Piattaforma sarà prima tentata di risolvere in via amichevole contattando legal@agentpick.co.

In caso di mancata risoluzione amichevole, le controversie saranno sottoposte alla giurisdizione esclusiva dei **tribunali italiani**, salvo che le norme imperative sulla protezione dei consumatori dell'UE prevedano diversamente (nel qual caso potrai anche adire i tribunali del tuo Paese di residenza).

I consumatori UE hanno inoltre il diritto di utilizzare la **piattaforma ODR (Online Dispute Resolution) dell'UE**: https://ec.europa.eu/consumers/odr

---

## 14. Disposizioni Generali

- **Accordo Completo:** I presenti Termini, unitamente all'Informativa sulla Privacy, alla Cookie Policy e (per i creatori) al Contratto per Creatori, costituiscono l'intero accordo tra te e AgentPick.
- **Nullità Parziale:** Se una disposizione dei presenti Termini risultasse inapplicabile, le disposizioni rimanenti continueranno ad avere piena efficacia.
- **Nessuna Rinuncia:** Il mancato esercizio di un diritto o di una disposizione da parte nostra non costituisce rinuncia a tale diritto.
- **Cessione:** Non puoi cedere i tuoi diritti ai sensi dei presenti Termini senza il nostro consenso scritto. Possiamo cedere i nostri diritti in caso di fusione, acquisizione o vendita di asset.
- **Lingua:** La versione in lingua italiana è quella prevalente ai fini della legge italiana. La versione inglese è fornita per comodità.

---

## 15. Contatti

**AgentPick**  
agentpick.co  
Email: legal@agentpick.co`;

const content: Record<string, string> = {
  en: TERMS_EN,
  it: TERMS_IT,
};

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!content[locale]) notFound();

  return (
    <main className="min-h-screen bg-gray-950 text-white font-[family-name:var(--font-geist-sans)]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <article className="prose prose-invert prose-purple max-w-none">
          <ReactMarkdown>{content[locale]}</ReactMarkdown>
        </article>
        <div className="mt-16 pt-8 border-t border-white/10 text-sm text-gray-500 flex gap-6">
          <a href={`/${locale}/privacy`} className="hover:text-purple-400 transition-colors">
            {locale === "it" ? "Privacy Policy" : "Privacy Policy"}
          </a>
          <a href={`/${locale}/cookies`} className="hover:text-purple-400 transition-colors">
            Cookie Policy
          </a>
          <a href={`/${locale}`} className="hover:text-purple-400 transition-colors">
            ← {locale === "it" ? "Torna alla home" : "Back to home"}
          </a>
        </div>
      </div>
    </main>
  );
}
